# Generated by Django 3.1.6 on 2021-02-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='null', max_length=130),
            preserve_default=False,
        ),
    ]
