# Generated by Django 3.0 on 2020-12-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=300)),
                ('lname', models.CharField(max_length=300)),
            ],
        ),
    ]
